FROM node:20-alpine
WORKDIR "/workspace/batch"
RUN apk update && apk upgrade
RUN apk add --no-cache vim git openssl python3

# venvにpykakasiをインストール。&&で繋げる必要がある
RUN python3 -m venv /path/to/venv && . /path/to/venv/bin/activate && pip3 install pykakasi && deactivate