version: "3.8"

services:
  api:
    build:
      context: ./api
    tty: true
    stdin_open: true
    volumes:
      - ..:/workspace
      - api_store:/workspace/server/api/node_modules
    command: >
      sh -c 
        "yarn && yarn dev"
    ports:
      - "8080:8080"
    depends_on:
      - db

  batch:
    build:
      context: ./batch
    tty: true
    stdin_open: true
    volumes:
      - ..:/workspace
      - batch_store:/workspace/server/batch/node_modules
    command: >
      sh -c 
        "yarn && tail -f /dev/null"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: pgdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_store:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_store:
  api_store:
  batch_store: