version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: pgdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_store:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_store:
