### 生存確認用のエンドポイント
GET http://localhost:8080/health

### 音声情報を個別取得
GET http://localhost:8080/sound-info/single/1

### 音声情報を検索（条件指定なし）
GET http://localhost:8080/sound-info/search

### 音声情報を検索（「a」という文字列で検索）
GET http://localhost:8080/sound-info/search?q=a

### 音声情報を検索（作成日順でソート）
GET http://localhost:8080/sound-info/search?sort=created

### 音声情報を検索（再生回数順でソート）
GET http://localhost:8080/sound-info/search?sort=count

### 音声情報を検索（ページ指定あり）
GET http://localhost:8080/sound-info/search?page=1

### 音声情報を検索（ページ指定あり）
GET http://localhost:8080/sound-info/search?page=10000

### Signup
POST http://localhost:8080/auth/signup
content-type: application/json

{
  "name": "kat",
  "email": "katkatprog@example.com",
  "password": "P@ssw0rd"
}

### Signin
POST http://localhost:8080/auth/signin
content-type: application/json

{
  "email": "katkatprog@example.com",
  "password": "P@ssw0rd"
}

### login-user
GET http://localhost:8080/login-user
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJpYXQiOjE3MjM0NjY1NDksImV4cCI6MTcyMzU1Mjk0OX0.Q7VcD695c2xWTc0ec_ONyB17bxx7iPfEkf4K_oNn7yU