name: batch-ci

on:
  push:
    branches:
      - "*"
    paths:
      - "batch/**"
      - ".github/**"

defaults:
  run:
    working-directory: batch

jobs:
  # CI実行
  # Dockerイメージのビルド時にESLint, Prettierの指摘がある、もしくはテストに通らない場合、後続のデプロイに進まない
  integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: do integrate
        run: docker image build -t batch-image:latest .
