name: batch-ci

on:
  push:
    branches:
      - "*"
    paths:
      - "batch/**"
      - ".github/**"

defaults:
  run:
    working-directory: batch

jobs:
  # CI実行(違反があるならエラーにする)
  integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: do integrate
        run: yarn && yarn checkformat && yarn lint
        
  # テスト実行
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: do test
        run: yarn && yarn test
